[run]
num_threads = 1
buffer_pool_size = 200KB
fd_limit = 5000
num_retained_archives = 0
archive_interval_secs = 60
skip_verify_checksum = false
#manifest_limit = 100000000

[permanent]
store_path = /mnt/d1/eloqstore_bench
data_page_size = 4KB
data_file_size = 8MB
data_append_mode = true
