#pragma once

#include "write_task.h"

namespace kvstore
{

class BatchWriteTask : public WriteTask
{
public:
    TaskType Type() const override
    {
        return TaskType::BatchWrite;
    }
    void Abort() override;

    bool SetBatch(std::vector<WriteDataEntry> &&entries);
    KvError Apply();

private:
    KvError LoadApplyingPage(PageId page_id);
    KvError ApplyOnePage(size_t &cidx);
    std::pair<MemIndexPage *, KvError> Pop();

    KvError FinishIndexPage(MemIndexPage *new_page,
                            std::string idx_page_key,
                            PageId page_id,
                            bool elevate);
    KvError FinishDataPage(std::string_view page_view,
                           std::string page_key,
                           PageId page_id);

    /**
     * @brief Pops up the index stack such that the top index entry contains the
     * search key.
     *
     * @param search_key
     */
    KvError SeekStack(std::string_view search_key);

    std::vector<WriteDataEntry> batch_;
    DataPage applying_page_;

    /**
     * @brief To maintain the double link list between bottom data pages, we
     * keep at most three adjacent data pages in memory. [1] is the page
     * ApplyOnePage currently writing to, [0] is the previous page of [1], and
     * [2] is the next page of [1].
     */
    DataPage leaf_triple_[3];
    /**
     * @brief Get triple element at position idx.
     *
     * @param idx The element position, can be 0, 1 or 2.
     */
    DataPage *TripleElement(uint8_t idx);
    /**
     * @brief Load leaf data page from disk to leaf_triple_[idx].
     *
     * @param idx The element position, can be 0 or 2.
     */
    KvError LoadTripleElement(uint8_t idx, PageId page_id);

    /**
     * @brief Update element in leaf link list. Replace the old page at
     * applying_page_ with new page. The new page is the first page generated by
     * ApplyOnePage.
     *
     * @param page The new page.
     * @param old_fp File page id of the old page.
     */
    KvError LeafLinkUpdate(DataPage &&page);
    /**
     * @brief Insert new page into leaf link list.
     *
     * @param page The new page.
     */
    KvError LeafLinkInsert(DataPage &&page);
    /**
     * @brief Delete the old data page at applying_page_ from leaf link list.
     */
    KvError LeafLinkDelete();
    KvError ShiftLeafLink();
};

}  // namespace kvstore