add_test( [==[batch entry with smaller timestamp]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[batch entry with smaller timestamp]==]  )
set_tests_properties( [==[batch entry with smaller timestamp]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[mixed batch write with read]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[mixed batch write with read]==]  )
set_tests_properties( [==[mixed batch write with read]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[truncate from the first key]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[truncate from the first key]==]  )
set_tests_properties( [==[truncate from the first key]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[truncate twice overflow values]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[truncate twice overflow values]==]  )
set_tests_properties( [==[truncate twice overflow values]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[batch write with big key]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[batch write with big key]==]  )
set_tests_properties( [==[batch write with big key]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[batch write abort releases pinned index pages]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[batch write abort releases pinned index pages]==]  )
set_tests_properties( [==[batch write abort releases pinned index pages]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[batch write task pool handles many partitions concurrently]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[batch write task pool handles many partitions concurrently]==]  )
set_tests_properties( [==[batch write task pool handles many partitions concurrently]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[batch write arguments]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[batch write arguments]==]  )
set_tests_properties( [==[batch write arguments]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[batch write task pool cleaned after abort]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write [==[batch write task pool cleaned after abort]==]  )
set_tests_properties( [==[batch write task pool cleaned after abort]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( batch_write_TESTS [==[batch entry with smaller timestamp]==] [==[mixed batch write with read]==] [==[truncate from the first key]==] [==[truncate twice overflow values]==] [==[batch write with big key]==] [==[batch write abort releases pinned index pages]==] [==[batch write task pool handles many partitions concurrently]==] [==[batch write arguments]==] [==[batch write task pool cleaned after abort]==])
