if(EXISTS "/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write_tests-b12d07c.cmake")
  include("/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/batch_write_tests-b12d07c.cmake")
else()
  add_test(batch_write_NOT_BUILT-b12d07c batch_write_NOT_BUILT-b12d07c)
endif()
