add_test( [==[file size tests - different page sizes]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/chore [==[file size tests - different page sizes]==]  )
set_tests_properties( [==[file size tests - different page sizes]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[file size tests - different file sizes]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/chore [==[file size tests - different file sizes]==]  )
set_tests_properties( [==[file size tests - different file sizes]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[file size tests - massive data injection]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/chore [==[file size tests - massive data injection]==]  )
set_tests_properties( [==[file size tests - massive data injection]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[file size tests - extreme page count per file]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/chore [==[file size tests - extreme page count per file]==]  )
set_tests_properties( [==[file size tests - extreme page count per file]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[file size tests - mixed page and file size combinations]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/chore [==[file size tests - mixed page and file size combinations]==]  )
set_tests_properties( [==[file size tests - mixed page and file size combinations]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( chore_TESTS [==[file size tests - different page sizes]==] [==[file size tests - different file sizes]==] [==[file size tests - massive data injection]==] [==[file size tests - extreme page count per file]==] [==[file size tests - mixed page and file size combinations]==])
