if(EXISTS "/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/chore_tests-b12d07c.cmake")
  include("/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/chore_tests-b12d07c.cmake")
else()
  add_test(chore_NOT_BUILT-b12d07c chore_NOT_BUILT-b12d07c)
endif()
