if(EXISTS "/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud_tests-b12d07c.cmake")
  include("/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud_tests-b12d07c.cmake")
else()
  add_test(cloud_NOT_BUILT-b12d07c cloud_NOT_BUILT-b12d07c)
endif()
