add_test( [==[simple cloud store]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[simple cloud store]==]  )
set_tests_properties( [==[simple cloud store]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud prewarm downloads while shards idle]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud prewarm downloads while shards idle]==]  )
set_tests_properties( [==[cloud prewarm downloads while shards idle]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud prewarm supports writes after restart]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud prewarm supports writes after restart]==]  )
set_tests_properties( [==[cloud prewarm supports writes after restart]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud reopen waits on evicting cached file]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud reopen waits on evicting cached file]==]  )
set_tests_properties( [==[cloud reopen waits on evicting cached file]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud prewarm respects cache budget]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud prewarm respects cache budget]==]  )
set_tests_properties( [==[cloud prewarm respects cache budget]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud reuse cache enforces budgets across restarts]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud reuse cache enforces budgets across restarts]==]  )
set_tests_properties( [==[cloud reuse cache enforces budgets across restarts]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud prewarm honors partition filter]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud prewarm honors partition filter]==]  )
set_tests_properties( [==[cloud prewarm honors partition filter]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud prewarm handles pagination with 2000+ files]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud prewarm handles pagination with 2000+ files]==]  )
set_tests_properties( [==[cloud prewarm handles pagination with 2000+ files]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud prewarm queue management with producer blocking]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud prewarm queue management with producer blocking]==]  )
set_tests_properties( [==[cloud prewarm queue management with producer blocking]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud prewarm aborts gracefully when disk fills]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud prewarm aborts gracefully when disk fills]==]  )
set_tests_properties( [==[cloud prewarm aborts gracefully when disk fills]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud gc preserves archived data after truncate]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud gc preserves archived data after truncate]==]  )
set_tests_properties( [==[cloud gc preserves archived data after truncate]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud global archive shares timestamp and filters partitions]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud global archive shares timestamp and filters partitions]==]  )
set_tests_properties( [==[cloud global archive shares timestamp and filters partitions]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud store with restart]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud store with restart]==]  )
set_tests_properties( [==[cloud store with restart]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud reopen refreshes manifest via archive swap]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud reopen refreshes manifest via archive swap]==]  )
set_tests_properties( [==[cloud reopen refreshes manifest via archive swap]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud reopen refreshes local manifest from remote]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud reopen refreshes local manifest from remote]==]  )
set_tests_properties( [==[cloud reopen refreshes local manifest from remote]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud reopen triggers prewarm to download newer remote data files]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud reopen triggers prewarm to download newer remote data files]==]  )
set_tests_properties( [==[cloud reopen triggers prewarm to download newer remote data files]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud global reopen refreshes local manifests]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud global reopen refreshes local manifests]==]  )
set_tests_properties( [==[cloud global reopen refreshes local manifests]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud store cached file LRU]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[cloud store cached file LRU]==]  )
set_tests_properties( [==[cloud store cached file LRU]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[concurrent test with cloud]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[concurrent test with cloud]==]  )
set_tests_properties( [==[concurrent test with cloud]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[easy cloud rollback to archive]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[easy cloud rollback to archive]==]  )
set_tests_properties( [==[easy cloud rollback to archive]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[enhanced cloud rollback with mix operations]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[enhanced cloud rollback with mix operations]==]  )
set_tests_properties( [==[enhanced cloud rollback with mix operations]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[archive triggers with cloud-only partitions]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/cloud [==[archive triggers with cloud-only partitions]==]  )
set_tests_properties( [==[archive triggers with cloud-only partitions]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( cloud_TESTS [==[simple cloud store]==] [==[cloud prewarm downloads while shards idle]==] [==[cloud prewarm supports writes after restart]==] [==[cloud reopen waits on evicting cached file]==] [==[cloud prewarm respects cache budget]==] [==[cloud reuse cache enforces budgets across restarts]==] [==[cloud prewarm honors partition filter]==] [==[cloud prewarm handles pagination with 2000+ files]==] [==[cloud prewarm queue management with producer blocking]==] [==[cloud prewarm aborts gracefully when disk fills]==] [==[cloud gc preserves archived data after truncate]==] [==[cloud global archive shares timestamp and filters partitions]==] [==[cloud store with restart]==] [==[cloud reopen refreshes manifest via archive swap]==] [==[cloud reopen refreshes local manifest from remote]==] [==[cloud reopen triggers prewarm to download newer remote data files]==] [==[cloud global reopen refreshes local manifests]==] [==[cloud store cached file LRU]==] [==[concurrent test with cloud]==] [==[easy cloud rollback to archive]==] [==[enhanced cloud rollback with mix operations]==] [==[archive triggers with cloud-only partitions]==])
