add_test( [==[concurrently write to partition]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/concurrency [==[concurrently write to partition]==]  )
set_tests_properties( [==[concurrently write to partition]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[easy concurrency test]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/concurrency [==[easy concurrency test]==]  )
set_tests_properties( [==[easy concurrency test]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[hard concurrency test]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/concurrency [==[hard concurrency test]==]  )
set_tests_properties( [==[hard concurrency test]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[stress append only mode]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/concurrency [==[stress append only mode]==]  )
set_tests_properties( [==[stress append only mode]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( concurrency_TESTS [==[concurrently write to partition]==] [==[easy concurrency test]==] [==[hard concurrency test]==] [==[stress append only mode]==])
