add_test( [==[simple delete]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[simple delete]==]  )
set_tests_properties( [==[simple delete]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[delete from an empty table]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[delete from an empty table]==]  )
set_tests_properties( [==[delete from an empty table]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[clean data]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[clean data]==]  )
set_tests_properties( [==[clean data]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[decrease height]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[decrease height]==]  )
set_tests_properties( [==[decrease height]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[random upsert/delete and scan]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[random upsert/delete and scan]==]  )
set_tests_properties( [==[random upsert/delete and scan]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[easy truncate table partition]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[easy truncate table partition]==]  )
set_tests_properties( [==[easy truncate table partition]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[truncate table partition]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[truncate table partition]==]  )
set_tests_properties( [==[truncate table partition]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[rand write with expire timestamp]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[rand write with expire timestamp]==]  )
set_tests_properties( [==[rand write with expire timestamp]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[write expired keys]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[write expired keys]==]  )
set_tests_properties( [==[write expired keys]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[upsert with expire timestamp]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[upsert with expire timestamp]==]  )
set_tests_properties( [==[upsert with expire timestamp]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[expire timestamp]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/delete [==[expire timestamp]==]  )
set_tests_properties( [==[expire timestamp]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( delete_TESTS [==[simple delete]==] [==[delete from an empty table]==] [==[clean data]==] [==[decrease height]==] [==[random upsert/delete and scan]==] [==[easy truncate table partition]==] [==[truncate table partition]==] [==[rand write with expire timestamp]==] [==[write expired keys]==] [==[upsert with expire timestamp]==] [==[expire timestamp]==])
