add_test( [==[EloqStore ValidateOptions validates all parameters]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[EloqStore ValidateOptions validates all parameters]==]  )
set_tests_properties( [==[EloqStore ValidateOptions validates all parameters]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[EloqStore Start validates local store paths]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[EloqStore Start validates local store paths]==]  )
set_tests_properties( [==[EloqStore Start validates local store paths]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[EloqStore basic lifecycle management]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[EloqStore basic lifecycle management]==]  )
set_tests_properties( [==[EloqStore basic lifecycle management]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[EloqStore handles multiple start calls]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[EloqStore handles multiple start calls]==]  )
set_tests_properties( [==[EloqStore handles multiple start calls]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[EloqStore handles multiple stop calls]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[EloqStore handles multiple stop calls]==]  )
set_tests_properties( [==[EloqStore handles multiple stop calls]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[EloqStore handles requests when stopped]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[EloqStore handles requests when stopped]==]  )
set_tests_properties( [==[EloqStore handles requests when stopped]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[CircularQueue rejects zero capacity]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[CircularQueue rejects zero capacity]==]  )
set_tests_properties( [==[CircularQueue rejects zero capacity]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[CircularQueue reset rejects zero capacity]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[CircularQueue reset rejects zero capacity]==]  )
set_tests_properties( [==[CircularQueue reset rejects zero capacity]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[CircularQueue reset assigns new capacity]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[CircularQueue reset assigns new capacity]==]  )
set_tests_properties( [==[CircularQueue reset assigns new capacity]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[CircularQueue EnqueueAsFirst prepends items]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/eloq_store_test [==[CircularQueue EnqueueAsFirst prepends items]==]  )
set_tests_properties( [==[CircularQueue EnqueueAsFirst prepends items]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( eloq_store_test_TESTS [==[EloqStore ValidateOptions validates all parameters]==] [==[EloqStore Start validates local store paths]==] [==[EloqStore basic lifecycle management]==] [==[EloqStore handles multiple start calls]==] [==[EloqStore handles multiple stop calls]==] [==[EloqStore handles requests when stopped]==] [==[CircularQueue rejects zero capacity]==] [==[CircularQueue reset rejects zero capacity]==] [==[CircularQueue reset assigns new capacity]==] [==[CircularQueue EnqueueAsFirst prepends items]==])
