add_test( [==[ParseFileName - basic parsing]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseFileName - basic parsing]==]  )
set_tests_properties( [==[ParseFileName - basic parsing]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseFileName - edge cases]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseFileName - edge cases]==]  )
set_tests_properties( [==[ParseFileName - edge cases]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseDataFileSuffix - legacy format rejected]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseDataFileSuffix - legacy format rejected]==]  )
set_tests_properties( [==[ParseDataFileSuffix - legacy format rejected]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseDataFileSuffix - term-aware format]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseDataFileSuffix - term-aware format]==]  )
set_tests_properties( [==[ParseDataFileSuffix - term-aware format]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseDataFileSuffix - edge cases]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseDataFileSuffix - edge cases]==]  )
set_tests_properties( [==[ParseDataFileSuffix - edge cases]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseManifestFileSuffix - legacy format rejected]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseManifestFileSuffix - legacy format rejected]==]  )
set_tests_properties( [==[ParseManifestFileSuffix - legacy format rejected]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseManifestFileSuffix - term-only format]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseManifestFileSuffix - term-only format]==]  )
set_tests_properties( [==[ParseManifestFileSuffix - term-only format]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseManifestFileSuffix - term-aware archive format]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseManifestFileSuffix - term-aware archive format]==]  )
set_tests_properties( [==[ParseManifestFileSuffix - term-aware archive format]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseManifestFileSuffix - edge cases]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseManifestFileSuffix - edge cases]==]  )
set_tests_properties( [==[ParseManifestFileSuffix - edge cases]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[DataFileName - term-aware format]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[DataFileName - term-aware format]==]  )
set_tests_properties( [==[DataFileName - term-aware format]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ManifestFileName - term-aware format]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ManifestFileName - term-aware format]==]  )
set_tests_properties( [==[ManifestFileName - term-aware format]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ArchiveName - term-aware format]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ArchiveName - term-aware format]==]  )
set_tests_properties( [==[ArchiveName - term-aware format]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[Roundtrip - DataFileName generate and parse]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[Roundtrip - DataFileName generate and parse]==]  )
set_tests_properties( [==[Roundtrip - DataFileName generate and parse]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[Roundtrip - ManifestFileName generate and parse]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[Roundtrip - ManifestFileName generate and parse]==]  )
set_tests_properties( [==[Roundtrip - ManifestFileName generate and parse]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[Roundtrip - ArchiveName generate and parse]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[Roundtrip - ArchiveName generate and parse]==]  )
set_tests_properties( [==[Roundtrip - ArchiveName generate and parse]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseUint64 - valid numbers]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseUint64 - valid numbers]==]  )
set_tests_properties( [==[ParseUint64 - valid numbers]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ParseUint64 - invalid inputs]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[ParseUint64 - invalid inputs]==]  )
set_tests_properties( [==[ParseUint64 - invalid inputs]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[Integration - complete filename workflow]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing [==[Integration - complete filename workflow]==]  )
set_tests_properties( [==[Integration - complete filename workflow]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( filename_parsing_TESTS [==[ParseFileName - basic parsing]==] [==[ParseFileName - edge cases]==] [==[ParseDataFileSuffix - legacy format rejected]==] [==[ParseDataFileSuffix - term-aware format]==] [==[ParseDataFileSuffix - edge cases]==] [==[ParseManifestFileSuffix - legacy format rejected]==] [==[ParseManifestFileSuffix - term-only format]==] [==[ParseManifestFileSuffix - term-aware archive format]==] [==[ParseManifestFileSuffix - edge cases]==] [==[DataFileName - term-aware format]==] [==[ManifestFileName - term-aware format]==] [==[ArchiveName - term-aware format]==] [==[Roundtrip - DataFileName generate and parse]==] [==[Roundtrip - ManifestFileName generate and parse]==] [==[Roundtrip - ArchiveName generate and parse]==] [==[ParseUint64 - valid numbers]==] [==[ParseUint64 - invalid inputs]==] [==[Integration - complete filename workflow]==])
