add_test( [==[FileIdTermMapping serialize/deserialize roundtrip]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/fileid_term_mapping [==[FileIdTermMapping serialize/deserialize roundtrip]==]  )
set_tests_properties( [==[FileIdTermMapping serialize/deserialize roundtrip]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[FileIdTermMapping empty mapping]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/fileid_term_mapping [==[FileIdTermMapping empty mapping]==]  )
set_tests_properties( [==[FileIdTermMapping empty mapping]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[FileIdTermMapping malformed data]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/fileid_term_mapping [==[FileIdTermMapping malformed data]==]  )
set_tests_properties( [==[FileIdTermMapping malformed data]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[FileIdTermMapping truncated count]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/fileid_term_mapping [==[FileIdTermMapping truncated count]==]  )
set_tests_properties( [==[FileIdTermMapping truncated count]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( fileid_term_mapping_TESTS [==[FileIdTermMapping serialize/deserialize roundtrip]==] [==[FileIdTermMapping empty mapping]==] [==[FileIdTermMapping malformed data]==] [==[FileIdTermMapping truncated count]==])
