if(EXISTS "/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing_tests-b12d07c.cmake")
  include("/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/filename_parsing_tests-b12d07c.cmake")
else()
  add_test(filename_parsing_NOT_BUILT-b12d07c filename_parsing_NOT_BUILT-b12d07c)
endif()
