if(EXISTS "/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/fileid_term_mapping_tests-b12d07c.cmake")
  include("/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/fileid_term_mapping_tests-b12d07c.cmake")
else()
  add_test(fileid_term_mapping_NOT_BUILT-b12d07c fileid_term_mapping_NOT_BUILT-b12d07c)
endif()
