if(EXISTS "/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/gc_tests-b12d07c.cmake")
  include("/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/gc_tests-b12d07c.cmake")
else()
  add_test(gc_NOT_BUILT-b12d07c gc_NOT_BUILT-b12d07c)
endif()
