add_test( [==[cloud mode truncate remote directory cleanup]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/gc [==[cloud mode truncate remote directory cleanup]==]  )
set_tests_properties( [==[cloud mode truncate remote directory cleanup]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud mode delete all data remote cleanup]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/gc [==[cloud mode delete all data remote cleanup]==]  )
set_tests_properties( [==[cloud mode delete all data remote cleanup]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[archive prevents data deletion after truncate]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/gc [==[archive prevents data deletion after truncate]==]  )
set_tests_properties( [==[archive prevents data deletion after truncate]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[cloud mode repeated truncate with directory purge]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/gc [==[cloud mode repeated truncate with directory purge]==]  )
set_tests_properties( [==[cloud mode repeated truncate with directory purge]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( gc_TESTS [==[cloud mode truncate remote directory cleanup]==] [==[cloud mode delete all data remote cleanup]==] [==[archive prevents data deletion after truncate]==] [==[cloud mode repeated truncate with directory purge]==])
