if(EXISTS "/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest_tests-b12d07c.cmake")
  include("/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest_tests-b12d07c.cmake")
else()
  add_test(manifest_NOT_BUILT-b12d07c manifest_NOT_BUILT-b12d07c)
endif()
