add_test( [==[simple manifest recovery]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[simple manifest recovery]==]  )
set_tests_properties( [==[simple manifest recovery]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[medium manifest recovery]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[medium manifest recovery]==]  )
set_tests_properties( [==[medium manifest recovery]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[create archives]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[create archives]==]  )
set_tests_properties( [==[create archives]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[global archive shares timestamp and filters partitions]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[global archive shares timestamp and filters partitions]==]  )
set_tests_properties( [==[global archive shares timestamp and filters partitions]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[global archive handles more partitions than max_archive_tasks]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[global archive handles more partitions than max_archive_tasks]==]  )
set_tests_properties( [==[global archive handles more partitions than max_archive_tasks]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[easy rollback to archive]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[easy rollback to archive]==]  )
set_tests_properties( [==[easy rollback to archive]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[enhanced rollback with mix operations]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[enhanced rollback with mix operations]==]  )
set_tests_properties( [==[enhanced rollback with mix operations]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[rootmeta eviction with small cache across partitions]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[rootmeta eviction with small cache across partitions]==]  )
set_tests_properties( [==[rootmeta eviction with small cache across partitions]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[rootmeta eviction tolerates active writers]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[rootmeta eviction tolerates active writers]==]  )
set_tests_properties( [==[rootmeta eviction tolerates active writers]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[manifest tolerates trailing corruption]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/manifest [==[manifest tolerates trailing corruption]==]  )
set_tests_properties( [==[manifest tolerates trailing corruption]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( manifest_TESTS [==[simple manifest recovery]==] [==[medium manifest recovery]==] [==[create archives]==] [==[global archive shares timestamp and filters partitions]==] [==[global archive handles more partitions than max_archive_tasks]==] [==[easy rollback to archive]==] [==[enhanced rollback with mix operations]==] [==[rootmeta eviction with small cache across partitions]==] [==[rootmeta eviction tolerates active writers]==] [==[manifest tolerates trailing corruption]==])
