add_test( [==[simple persist]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[simple persist]==]  )
set_tests_properties( [==[simple persist]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[complex persist]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[complex persist]==]  )
set_tests_properties( [==[complex persist]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[persist with restart]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[persist with restart]==]  )
set_tests_properties( [==[persist with restart]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[drop table clears all partitions]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[drop table clears all partitions]==]  )
set_tests_properties( [==[drop table clears all partitions]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[simple LRU for opened fd]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[simple LRU for opened fd]==]  )
set_tests_properties( [==[simple LRU for opened fd]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[complex LRU for opened fd]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[complex LRU for opened fd]==]  )
set_tests_properties( [==[complex LRU for opened fd]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[detect corrupted page]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[detect corrupted page]==]  )
set_tests_properties( [==[detect corrupted page]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[overflow kv]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[overflow kv]==]  )
set_tests_properties( [==[overflow kv]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[random overflow kv]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[random overflow kv]==]  )
set_tests_properties( [==[random overflow kv]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[concurrency with overflow kv]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[concurrency with overflow kv]==]  )
set_tests_properties( [==[concurrency with overflow kv]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[easy append only mode]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[easy append only mode]==]  )
set_tests_properties( [==[easy append only mode]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[hard append only mode]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[hard append only mode]==]  )
set_tests_properties( [==[hard append only mode]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[file garbage collector]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[file garbage collector]==]  )
set_tests_properties( [==[file garbage collector]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[append mode with restart]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[append mode with restart]==]  )
set_tests_properties( [==[append mode with restart]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[append mode survives compression toggles across restarts]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist [==[append mode survives compression toggles across restarts]==]  )
set_tests_properties( [==[append mode survives compression toggles across restarts]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( persist_TESTS [==[simple persist]==] [==[complex persist]==] [==[persist with restart]==] [==[drop table clears all partitions]==] [==[simple LRU for opened fd]==] [==[complex LRU for opened fd]==] [==[detect corrupted page]==] [==[overflow kv]==] [==[random overflow kv]==] [==[concurrency with overflow kv]==] [==[easy append only mode]==] [==[hard append only mode]==] [==[file garbage collector]==] [==[append mode with restart]==] [==[append mode survives compression toggles across restarts]==])
