if(EXISTS "/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist_tests-b12d07c.cmake")
  include("/home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/persist_tests-b12d07c.cmake")
else()
  add_test(persist_NOT_BUILT-b12d07c persist_NOT_BUILT-b12d07c)
endif()
