add_test( [==[delete scan]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/scan [==[delete scan]==]  )
set_tests_properties( [==[delete scan]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[complex scan]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/scan [==[complex scan]==]  )
set_tests_properties( [==[complex scan]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[random write and scan]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/scan [==[random write and scan]==]  )
set_tests_properties( [==[random write and scan]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[paginate the scan results]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/scan [==[paginate the scan results]==]  )
set_tests_properties( [==[paginate the scan results]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[read floor]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/scan [==[read floor]==]  )
set_tests_properties( [==[read floor]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( scan_TESTS [==[delete scan]==] [==[complex scan]==] [==[random write and scan]==] [==[paginate the scan results]==] [==[read floor]==])
