add_test( [==[ComputeStorePathLut preserves ratios regardless of order]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/store_path_lut [==[ComputeStorePathLut preserves ratios regardless of order]==]  )
set_tests_properties( [==[ComputeStorePathLut preserves ratios regardless of order]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ComputeStorePathLut normalizes gcd]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/store_path_lut [==[ComputeStorePathLut normalizes gcd]==]  )
set_tests_properties( [==[ComputeStorePathLut normalizes gcd]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ComputeStorePathLut respects max entries]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/store_path_lut [==[ComputeStorePathLut respects max entries]==]  )
set_tests_properties( [==[ComputeStorePathLut respects max entries]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
add_test( [==[ComputeStorePathLut handles fractional-style ratios]==] /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests/store_path_lut [==[ComputeStorePathLut handles fractional-style ratios]==]  )
set_tests_properties( [==[ComputeStorePathLut handles fractional-style ratios]==] PROPERTIES WORKING_DIRECTORY /home/chenzhao/ssh-projects/eloqstore_standby_local/bld/tests)
set( store_path_lut_TESTS [==[ComputeStorePathLut preserves ratios regardless of order]==] [==[ComputeStorePathLut normalizes gcd]==] [==[ComputeStorePathLut respects max entries]==] [==[ComputeStorePathLut handles fractional-style ratios]==])
